export default {
  products: [
    {
      _id: "1",
      name: "Bob Gibson",
      category: "Pitchers",
      image: "./images/gibby68tops.jpg",
      price: 99,
      brand: "1968 Topps",
      rating: 9.2,
      reviews: 9,
    },
    {
      _id: "2",
      name: "Babe Ruth",
      category: "Hitters",
      image: "./images/ruth.jpg",
      price: 100,
      brand: "1948 Leaf",
      rating: 8.5,
      reviews: 22,
    },
    {
      _id: "3",
      name: "Rickey Henderson",
      category: "Hitters",
      image: "./images/rickey92score.jpg",
      price: 95,
      brand: "1992 Score",
      rating: 8.9,
      reviews: 2,
    },
    {
      _id: "4",
      name: "Ted Williams",
      category: "Hitters",
      image: "./images/ted.61fleer.jpg",
      price: 120,
      brand: "1961 Fleer",
      rating: 8.5,
      reviews: 17,
    },
    {
      _id: "5",
      name: "Ozzie Smith",
      category: "Hitters",
      image: "./images/ozzie01topps.jpg",
      price: 85,
      brand: "2001 Topps",
      rating: 9.4,
      reviews: 9,
    },
    {
      _id: "6",
      name: "Ken Griffey Jr.",
      category: "Hitters",
      image: "./images/kenupperdeck.jpg",
      price: 40,
      brand: "1989 Upper Deck",
      rating: 9.9,
      reviews: 12,
    },
    {
      _id: "7",
      name: "Nolan Ryan",
      category: "Pitchers",
      image: "./images/ryan.donruss90.jpg",
      price: 70,
      brand: "1990 Donruss",
      rating: 8.8,
      reviews: 9,
    },
    {
      _id: "8",
      name: "Mike Trout",
      category: "Hitters",
      image: "./images/trout98topps.jpg",
      price: 90,
      brand: "2018 Topps",
      rating: 9.8,
      reviews: 6,
    },
  ],
};
